### ISSUE TITLE
feat: add the cairo runner

### ISSUE THREAD

**Issue by greged93** [keep-starknet-strange/cairo-zig#155] opened 2023-11-16 11:40 UTC
In order to run the first cairo program, the cairo runner structure is needed. This runner takes care of setting up the the program and execution segments, setting the start values for `pc`, `ap` and `fp`.

**Comment by greged93** [comment] 2023-11-16 11:40
@lana-shanghai would love to pick this up over the weekend :)

**Comment by lana-shanghai** [comment] 2023-11-16 11:42
Please do! :)

**Comment by lana-shanghai** [comment] 2023-11-16 11:50
Please sync with @jobez to make sure you guys do not do any duplicate work! :)

**Comment by jobez** [comment] 2023-11-16 15:38
i read this issue as a duplicate of this: https://github.com/keep-starknet-strange/cairo-zig/issues/12

**Comment by greged93** [comment] 2023-11-16 15:41
Yes this was raised by Lana :) I was just searching in the issues and the code and couldn't find a reference to the runner, so that's why I added this, we can close if you prefer?

**Comment by jobez** [comment] 2023-11-16 15:49
sgtm, j't'apprecie. des temps il y a un issue que etais deja vu et c'est vraim d'accord. oui?

**Comment by lana-shanghai** [comment] 2023-11-16 15:56
> sgtm, j't'apprecie. des temps il y a un issue que etais deja vu et c'est vraim d'accord. oui?

oui oui bagette

**Closed** 2023-12-04 18:45 UTC
